application: engineapp0
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /blog/.*
  script: main.app
  
- url: /.*
  script: main.app
  
libraries:
- name: jinja2
  version: latest  